packages:
  - packages/*

autoInstallPeers: false
enableGlobalVirtualStore: false

peerDependencyRules:
  allowedVersions:
    'nunjucks>chokidar': '4'

allowBuilds:
  '@nestjs/core': true
  '@parcel/watcher': true
  core-js: false
  core-js-pure: false
  nx: true
  yarn: false
