packages:
  - packages/*

autoInstallPeers: false
enableGlobalVirtualStore: false

allowBuilds:
  '@nestjs/core': true
  '@parcel/watcher': true
  core-js: false
  core-js-pure: false
  esbuild: true
  nx: true
  yarn: false
