packages:
  - packages/*

autoInstallPeers: false
enableGlobalVirtualStore: false

allowBuilds:
  core-js: false
  core-js-pure: false
  esbuild: true
  nx: true
  yarn: false

minimumReleaseAgeExclude:
  - surgio@4.0.0-beta.1
